### ISSUE TITLE
sass task fails when styleIncludePaths option used

### ISSUE THREAD

**Issue by aaronlademann-wf** [Workiva/wGulp#150]
@theisensanders-wf reached out to me because he couldn't get the Sass API provided by [web-skin@1.1.0](https://github.com/Workiva/web-skin/releases/tag/1.1.0) to work in the certifier-client app.

I have determined that the sass task provided by wGulp is the problem, although I don't understand enough about gulp to know why.

When I add this sass task to the certifier-client app gulpfile... all works as expected:

```js
var sass = require('gulp-sass');
gulp.task('sass', function () {
  gulp.src('./sass/**/*.scss')
    .pipe(
        sass({
            includePaths: './node_modules/web-skin/sass'
        })
        .on('error', sass.logError)
    )
    .pipe(gulp.dest('./dist/css'));
});
```

The error can be seen on [this branch of certifier-client](https://github.com/theisensanders-wf/certifier-client/tree/testing-sass-api)

**Comment by maxwellpeterson-wf** [comment]
It appears this is resolved when I upgrade the `gulp-sass` to the latest version. Doing a clean install of wGulp to confirm, and then I'll get a new version of wGulp out.
FYI @theisensanders-wf
